title: CAMBIOS DE FORMA POKEMON
description: En este proyecto, exploramos cómo los Pokémon cambian su apariencia, tipo y habilidades al adaptarse a diferentes regiones, climas y situaciones.
![Image](https://github.com/user-attachments/assets/1b072c60-27c6-40c1-a3d5-508e0ad4b7c3)
theme: jekyll-theme-minimal

